// Code generated by mmapforge. DO NOT EDIT.

package example

import (
	mmapforge "github.com/CreditWorthy/mmapforge"
)

// MarketCapLayout returns the record layout for MarketCap.
// Fields are validated at code-generation time; ComputeLayout cannot fail here.
func MarketCapLayout() *mmapforge.RecordLayout {
	layout, _ := mmapforge.ComputeLayout([]mmapforge.FieldDef{
		{Name: "id", GoName: "ID", Type: 8, MaxSize: 0},
		{Name: "price", GoName: "Price", Type: 10, MaxSize: 0},
		{Name: "volume", GoName: "Volume", Type: 10, MaxSize: 0},
		{Name: "market_cap", GoName: "MarketCap", Type: 10, MaxSize: 0},
		{Name: "stale", GoName: "Stale", Type: 0, MaxSize: 0},
	})
	return layout
}

// MarketCapStore is the typed store for MarketCap records.
type MarketCapStore struct {
	*mmapforge.Store
}

// NewMarketCapStore creates a new MarketCap store at the given path.
func NewMarketCapStore(path string, opts ...mmapforge.StoreOption) (*MarketCapStore, error) {
	layout := MarketCapLayout()
	s, err := mmapforge.CreateStore(path, layout, 1, opts...)
	if err != nil {
		return nil, err
	}
	return &MarketCapStore{Store: s}, nil
}

// OpenMarketCapStore opens an existing MarketCap store at the given path.
func OpenMarketCapStore(path string, opts ...mmapforge.StoreOption) (*MarketCapStore, error) {
	layout := MarketCapLayout()
	s, err := mmapforge.OpenStore(path, layout, opts...)
	if err != nil {
		return nil, err
	}
	return &MarketCapStore{Store: s}, nil
}

// GetID returns the ID field for the record at idx.
func (s *MarketCapStore) GetID(idx int) (uint64, error) {
	for {
		seq := s.SeqReadBegin(idx)
		if seq&1 != 0 {
			continue
		}
		v, err := s.ReadUint64(idx, 8)
		if err != nil {
			return v, err
		}
		if s.SeqReadValid(idx, seq) {
			return v, nil
		}
	}
}

// SetID sets the ID field for the record at idx.
func (s *MarketCapStore) SetID(idx int, val uint64) error {
	s.SeqBeginWrite(idx)
	err := s.WriteUint64(idx, 8, val)
	s.SeqEndWrite(idx)
	return err
}

// GetPrice returns the Price field for the record at idx.
func (s *MarketCapStore) GetPrice(idx int) (float64, error) {
	for {
		seq := s.SeqReadBegin(idx)
		if seq&1 != 0 {
			continue
		}
		v, err := s.ReadFloat64(idx, 16)
		if err != nil {
			return v, err
		}
		if s.SeqReadValid(idx, seq) {
			return v, nil
		}
	}
}

// SetPrice sets the Price field for the record at idx.
func (s *MarketCapStore) SetPrice(idx int, val float64) error {
	s.SeqBeginWrite(idx)
	err := s.WriteFloat64(idx, 16, val)
	s.SeqEndWrite(idx)
	return err
}

// GetVolume returns the Volume field for the record at idx.
func (s *MarketCapStore) GetVolume(idx int) (float64, error) {
	for {
		seq := s.SeqReadBegin(idx)
		if seq&1 != 0 {
			continue
		}
		v, err := s.ReadFloat64(idx, 24)
		if err != nil {
			return v, err
		}
		if s.SeqReadValid(idx, seq) {
			return v, nil
		}
	}
}

// SetVolume sets the Volume field for the record at idx.
func (s *MarketCapStore) SetVolume(idx int, val float64) error {
	s.SeqBeginWrite(idx)
	err := s.WriteFloat64(idx, 24, val)
	s.SeqEndWrite(idx)
	return err
}

// GetMarketCap returns the MarketCap field for the record at idx.
func (s *MarketCapStore) GetMarketCap(idx int) (float64, error) {
	for {
		seq := s.SeqReadBegin(idx)
		if seq&1 != 0 {
			continue
		}
		v, err := s.ReadFloat64(idx, 32)
		if err != nil {
			return v, err
		}
		if s.SeqReadValid(idx, seq) {
			return v, nil
		}
	}
}

// SetMarketCap sets the MarketCap field for the record at idx.
func (s *MarketCapStore) SetMarketCap(idx int, val float64) error {
	s.SeqBeginWrite(idx)
	err := s.WriteFloat64(idx, 32, val)
	s.SeqEndWrite(idx)
	return err
}

// GetStale returns the Stale field for the record at idx.
func (s *MarketCapStore) GetStale(idx int) (bool, error) {
	for {
		seq := s.SeqReadBegin(idx)
		if seq&1 != 0 {
			continue
		}
		v, err := s.ReadBool(idx, 40)
		if err != nil {
			return v, err
		}
		if s.SeqReadValid(idx, seq) {
			return v, nil
		}
	}
}

// SetStale sets the Stale field for the record at idx.
func (s *MarketCapStore) SetStale(idx int, val bool) error {
	s.SeqBeginWrite(idx)
	err := s.WriteBool(idx, 40, val)
	s.SeqEndWrite(idx)
	return err
}

// MarketCapRecord holds all fields of a MarketCap record.
type MarketCapRecord struct {
	ID        uint64
	Price     float64
	Volume    float64
	MarketCap float64
	Stale     bool
}

// Get reads all fields atomically for the record at idx.
func (s *MarketCapStore) Get(idx int) (*MarketCapRecord, error) {
	for {
		seq := s.SeqReadBegin(idx)
		if seq&1 != 0 {
			continue
		}
		rec := &MarketCapRecord{}
		var err error
		rec.ID, err = s.ReadUint64(idx, 8)
		if err != nil {
			return nil, err
		}
		rec.Price, _ = s.ReadFloat64(idx, 16)
		rec.Volume, _ = s.ReadFloat64(idx, 24)
		rec.MarketCap, _ = s.ReadFloat64(idx, 32)
		rec.Stale, _ = s.ReadBool(idx, 40)
		if s.SeqReadValid(idx, seq) {
			return rec, nil
		}
	}
}

// Set writes all fields atomically for the record at idx.
func (s *MarketCapStore) Set(idx int, rec *MarketCapRecord) error {
	s.SeqBeginWrite(idx)
	if err := s.WriteUint64(idx, 8, rec.ID); err != nil {
		s.SeqEndWrite(idx)
		return err
	}
	_ = s.WriteFloat64(idx, 16, rec.Price)
	_ = s.WriteFloat64(idx, 24, rec.Volume)
	_ = s.WriteFloat64(idx, 32, rec.MarketCap)
	_ = s.WriteBool(idx, 40, rec.Stale)
	s.SeqEndWrite(idx)
	return nil
}
