package codegen

// DefaultHeader is used when Config.Header is empty.
const DefaultHeader = "// Code generated by mmapforge. DO NOT EDIT."

// Config holds the global codegen configuration, shared between all generated nodes.
type Config struct {
	// Target is the output directory for generated files.
	Target string

	// Package is the Go package for generated code.
	Package string

	// Header is an optional file header. Defaults to the DefaultHeader constant.
	Header string

	// Templates specifics optional external templates to execute
	// or override the defaults.
	Templates []*Template

	// Hooks holds an optional list of Hooks to apply on the graph
	// before/after code generation.
	Hooks []Hook
}

func (c *Config) header() string {
	if c.Header != "" {
		return c.Header
	}
	return DefaultHeader
}
