package codegen

const DefaultHeader = "// Code generated by mmapforge. DO NOT EDIT."

type Config struct {
	Target  string
	Package string
	Header  string

	Templates []*Template
	Hooks     []Hook
}

//func (c *Config) header() string {
//	if c.Header != "" {
//		return c.Header
//	}
//	return DefaultHeader
//}
